version: '2'
volumes:
  plex-data:
    driver: local
  seedbox-data:
    driver: local
services:
  deluge:
    image: jschulberger/deluge
    environment: 
    - ALLOWED_NETWORKS="10.10.0.0/24"
    stdin_open: true
    volumes:
    - seedbox-data:/home/deluge:rw
    tty: true
    ports:
    - ${WPORT}:8112/tcp
    labels:
      io.rancher.container.pull_image: always
  plex:
    image: plexinc/pms-docker
    stdin_open: true
    volumes:
    - plex-data:/data
    - /config
    - /transcode
    ports:
    - 32400:32400/tcp
    labels:
      io.rancher.container.pull_image: always
  sftp:
    image: atmoz/sftp
    stdin_open: true
    volumes:
    - ${SFTPKEY}:/home/sftp/.ssh/keys/sftp.pub:ro
    - seedbox-data:/home/sftp/seedbox:rw
    - plex-data:/home/sftp/plex:rw
    tty: true
    ports:
    - ${SFPORT}:22/tcp
    command:
    - 'sftp::::'
    labels:
      io.rancher.container.pull_image: always
