version: '2'
volumes:
  seedbox-data:
    driver: local
services:
  deluge:
    image: jschulberger/deluge
    stdin_open: true
    volumes:
    - seedbox-data:/home/deluge
    tty: true
    ports:
    - ${WPORT}:8112/tcp
    labels:
      io.rancher.container.pull_image: always
sftp:
  image:
    atmoz/sftp
    stdin_open: true
    volumes:
    - ${SFTPKEY}:/home/sftp/.ssh/keys/sftp.pub:ro
    - seedbox-data:/home/sftp/seedbox:rw
    tty: true
    ports:
    - ${SFPORT}:22/tcp
    command:
    - 'sftp::::'
    labels:
      io.rancher.container.pull_image: always
