.catalog:
  name: "Seedbox"
  version: "v0.1"
  description: "Seedbox powered by deluge with sftp support"
  uuid: seedbox-0
  questions:
    - variable: "WPORT"
      label: "Web port number"
      description: "Host port to be used for the web ui"
      default: 8112
      required: true
      type: "int"
    - variable: "SFPORT"
      label: "SFTP port number"
      description: "Host port to be used for SFTP"
      default: 2323
      required: true
      type: "int"
    - variable: "SFTPKEY"
      label: "SSH key for SFTP"
      description: "Path on the host that points to the public key (SFTP auth)"
      default: "/opt/service-keys/sftp.pub"
      required: true
      type: "string"
deluge:
    scale: 1
    start_on_create: true
sftp:
    scale: 1
    start_on_create: true
