version: '2'
services:
  mcmyadmin:
    scale: 1
    start_on_create: true
  sftp:
    scale: 1
    start_on_create: true
.catalog:
  name: minecraft-server
  versions: 0
  description: de
  questions:
    - variable: v
      label: l
      description: | d
      default: 8112
      required: true
      type: int